version: '3'
services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker  --accessLog --constraints=tag==my-stack # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mongo:3.4.10
  testa:
    build: app/
    restart: always
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.enable=true"
      - "traefik.port=5000"
      - "traefik.tags=my-stack"
  # nodejs app 1d
  # servertest:
  #   build: serverTest
  #   ports:
  #     - "18124:18123"
  #   links:
  #     - nginx:nginx
  #   restart: always
  server:
    build: server
    ports:
      - "1886:1886"
    links:
      - reverse-proxy:reverse-proxy
      -  db:mongo
    restart: always
